### ISSUE TITLE
Add support for BIAS-TEE

### ISSUE THREAD

**Issue by bebilder** [sdr-enthusiasts/docker-dump978#64]
It would be good to have an option similar to the readsb READSB_ENABLE_BIASTEE to enable BIAS-TEE on RTL-SDR devices when used with the dump978 container.

**Comment by kx1t** [comment]
Fixed the bias-tee script… should work now when you set `DUMP978_RTLSDR_BIASTEE=on`

closing issue, feel free to reopen it if it doesn’t work. 

https://github.com/sdr-enthusiasts/docker-dump978/commit/4fafebcf1bf17894866d056e1fbcb57931e58c1f
